import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Todo Next",
  description: "Generated by create next app",
  
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <link rel="shortcut icon" href="icon.svg" type="image/x-icon" />
      <body suppressHydrationWarning className='bg-white '>
        {children}
      </body>
    </html>
  );
}
